In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
from sklearn import preprocessing, model_selection
from sklearn.preprocessing import LabelEncoder


In [2]:
df = pd.read_csv('pok.csv')
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [3]:
# Просмотр типов покемонов
df['Type 1'].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [4]:
df['Type 2'].value_counts()

Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Water       14
Ghost       14
Ice         14
Rock        14
Fire        12
Electric     6
Normal       4
Bug          3
Name: Type 2, dtype: int64

In [5]:
# Составление двух массивов из типов покемонов и их харктеристик
x = np.array(df.drop(['Type 1', 'Type 2', 'Name', 'Legendary', '#', 'Generation'], axis = 1))
Y = np.array(df[['Type 1', 'Type 2']])

In [6]:
# Получившийся масив с типами покемонов
Y[:10, :]

array([['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ['Fire', nan],
       ['Fire', nan],
       ['Fire', 'Flying'],
       ['Fire', 'Dragon'],
       ['Fire', 'Flying'],
       ['Water', nan]], dtype=object)

In [7]:
# Перевод категориальных признаков в численные
labelencoder = LabelEncoder()
y1 = labelencoder.fit_transform(Y[:, 0])
y2 = labelencoder.fit_transform(Y[:, 1])

# Совмещение двух массивов и просмотр уникальных значений
y = np.column_stack((y1, y2))
print(y[:10, :])
print(len(set(y[:, 0])))
print(len(set(y[:, 1])))


[[ 9 13]
 [ 9 13]
 [ 9 13]
 [ 9 13]
 [ 6 18]
 [ 6 18]
 [ 6  7]
 [ 6  2]
 [ 6  7]
 [17 18]]
18
19


In [8]:
for i in range (10):
    print(x[i]," => ", y[i])


[318  45  49  49  65  65  45]  =>  [ 9 13]
[405  60  62  63  80  80  60]  =>  [ 9 13]
[525  80  82  83 100 100  80]  =>  [ 9 13]
[625  80 100 123 122 120  80]  =>  [ 9 13]
[309  39  52  43  60  50  65]  =>  [ 6 18]
[405  58  64  58  80  65  80]  =>  [ 6 18]
[534  78  84  78 109  85 100]  =>  [6 7]
[634  78 130 111 130  85 100]  =>  [6 2]
[634  78 104  78 159 115 100]  =>  [6 7]
[314  44  48  65  50  64  43]  =>  [17 18]


In [9]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, train_size = 0.6)

In [10]:
# Нормализация
x_f_train = preprocessing.scale(x_train)
x_f_test = preprocessing.scale(x_test)

print(y_train[:10, :])


[[ 2 10]
 [ 9 18]
 [ 1  5]
 [11 17]
 [13 18]
 [17 18]
 [ 0  9]
 [ 6 18]
 [ 9 13]
 [14 18]]


In [11]:
# Преобразование массива с типами покемонов в подходящий вид, где единица - это возможный тип покемона.

y_train_f = np.array([[0]*19]*len(y_train))
y_test_f = np.array([[0]*19]*len(y_test))

for i in range(len(y_test)):
    for j in range(2):
        y_test_f[i][y_test[i][j]] = 1

for i in range(len(y_train)):
    for j in range(2):
        y_train_f[i][y_train[i][j]] = 1
        
print(y_train_f[:10, :])
print('----------------------------------------')
print(y_test_f[:10, :])

[[0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]]
----------------------------------------
[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]]


In [12]:
# Построение нейронной сети с 7-ью входами и 19 выходами

inputs = tf.keras.Input(x_f_train[1].shape,)
x = tf.keras.layers.Dense(256, activation = tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(19, activation = tf.nn.softmax)(x)
model = tf.keras.Model(inputs = inputs, outputs = outputs)

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [35]:
model.fit(x_f_train, y_train_f, epochs=10)


Epoch 1/10
15/15 [==============================] - 0s 2ms/step - loss: 8.0252 - accuracy: 0.0625
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 8.5492 - accuracy: 0.0688
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 8.1837 - accuracy: 0.0646
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 8.1096 - accuracy: 0.0833
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 8.0095 - accuracy: 0.0396
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 8.1172 - accuracy: 0.0708
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 8.0743 - accuracy: 0.0562
Epoch 8/10
15/15 [==============================] - 0s 1ms/step - loss: 8.3154 - accuracy: 0.0750
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 8.6750 - accuracy: 0.0542
Epoch 10/10
15/15 [==============================] - 0s 1ms/step - loss: 8.7060 - accuracy: 0.0750


In [36]:
score, acc= model.evaluate(x_f_test, y_test_f)

# Обучение и тест не превосходят 15%, так как, по-моему мнению,
#датасет составлен не верно и по нему невозможно сделать качественную классивикацию

10/10 [==============================] - 0s 1ms/step - loss: 9.1584 - accuracy: 0.0812


In [37]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 7)]               0         
                                                                 
 dense (Dense)               (None, 256)               2048      
                                                                 
 dense_1 (Dense)             (None, 19)                4883      
                                                                 
Total params: 6,931
Trainable params: 6,931
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.predict(x_f_test)[:5, :]

10/10 [==============================] - 0s 1ms/step


array([[7.7028438e-03, 5.1593239e-04, 7.2213478e-02, 1.9202002e-03,
        1.6358757e-02, 5.5327456e-02, 8.7660760e-02, 5.4736298e-02,
        2.9283928e-02, 7.2655581e-02, 9.1250483e-03, 5.1151474e-06,
        1.2628729e-02, 3.1720642e-03, 1.3382997e-01, 1.0863781e-03,
        2.6147604e-02, 2.8742856e-01, 1.2820125e-01],
       [2.0154769e-02, 1.9740290e-03, 1.0887291e-02, 3.3559788e-02,
        4.8984427e-02, 2.4201734e-02, 4.5558292e-02, 1.4082707e-01,
        3.1349972e-02, 7.6800369e-02, 1.6588530e-03, 2.3860148e-04,
        4.5870792e-02, 1.0642880e-02, 2.1163885e-01, 4.2224920e-04,
        9.1994079e-03, 1.1177116e-01, 1.7425947e-01],
       [5.7802745e-03, 3.3534522e-04, 1.1658432e-05, 1.0140021e-01,
        3.7098702e-02, 5.1028037e-04, 2.4140589e-02, 7.0229299e-02,
        1.4863510e-02, 2.8896026e-02, 9.2779082e-06, 2.8760731e-04,
        1.1059114e-02, 1.2577252e-03, 9.4307944e-02, 4.7206652e-07,
        3.5919271e-05, 2.2112122e-02, 5.8766395e-01],
       [1.5543402e-02,